spring:
  profiles:
    active:
      - dev
---
server:
  port: 8767
spring:
  application:
    name: MICRO-SERVER-DEV
  profiles: dev #开发环境
---
server:
  port: 8868
spring:
  application:
    name: MICRO-SERVER-TEST
  profiles: test #测试环境

